package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"syscall"

	"github.com/spf13/cobra"
)

func init() { rootCmd.AddCommand(useCmd) }

var useCmd = &cobra.Command{
	Use:   "use [name]",
	Short: "Switch to a profile",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		name := args[0]

		// 🚫 Nếu đang trong subshell, chặn đổi profile
		if os.Getenv("SCTX_ACTIVE") == "1" {
			current := os.Getenv("SCTX_PROFILE")
			fmt.Printf("⚠️  You are currently inside profile %q.\n", current)
			fmt.Println("👉 Please type 'exit' to leave the subshell before switching to another profile.")
			return nil
		}

		home, _ := os.UserHomeDir()
		profileDir := filepath.Join(home, ".sctx", "profiles")
		profilePath := filepath.Join(profileDir, name)

		if _, err := os.Stat(profilePath); os.IsNotExist(err) {
			return fmt.Errorf("profile %q not found in %s", name, profileDir)
		}

		currentFile := filepath.Join(home, ".sctx", "current")
		if err := os.MkdirAll(filepath.Dir(currentFile), 0o755); err != nil {
			return err
		}

		if err := os.WriteFile(currentFile, []byte(name), 0o644); err != nil {
			return err
		}

		fmt.Printf("✅ switched to profile: %s\n", name)

		shell := os.Getenv("SHELL")
		if shell == "" {
			shell = "/bin/zsh"
		}

		// 🔧 Tạo thư mục tạm cho ZDOTDIR
		tempDir, err := os.MkdirTemp("", fmt.Sprintf("sctx-%s-*", name))
		if err != nil {
			return fmt.Errorf("failed to create temp dir: %w", err)
		}
		defer os.RemoveAll(tempDir)

		zshrcPath := filepath.Join(tempDir, ".zshrc")

		script := fmt.Sprintf(`# ~/.zshrc generated by sctx
export SCTX_PROFILE=%s
export SCTX_ACTIVE=1

# Source user's original .zshrc nếu có
if [[ -f "$HOME/.zshrc" ]]; then
  source "$HOME/.zshrc"
fi

# Hiển thị prefix màu đỏ
red=$'\033[1;31m'
reset=$'\033[0m'
PROMPT="[$red$SCTX_PROFILE$reset] %%n@%%m %%1~ %%# "
setopt PROMPT_SUBST

# Load profile thực tế của sctx
if [[ -f "%s" ]]; then
  source "%s"
fi

# Hook exit hiển thị log
function exit() {
  echo "👋 Leaving profile: $SCTX_PROFILE"
  builtin exit
}
`, name, profilePath, profilePath)

		if err := os.WriteFile(zshrcPath, []byte(script), 0o644); err != nil {
			return fmt.Errorf("failed to write zshrc: %w", err)
		}

		env := append(os.Environ(), fmt.Sprintf("ZDOTDIR=%s", tempDir))

		// ⚙️ Thay thế process hiện tại bằng zsh
		fmt.Printf("\033]0;[%s] sctx\007", name)
		fmt.Printf("\033[1;31m[%s]\033[0m subshell started. Type 'exit' to leave.\n", name)

		return syscall.Exec(shell, []string{shell}, env)
	},
}
